name: 'Medcrypt Helm SBOM Upload'
description: 'Upload a SBOM into Medcrypt Helm system'
author: 'Medcrypt'

inputs:
  api-base-url:
    description: 'The root URL for the Medcrypt Helm API. This determines your environment'
    required: true
  client-id:
    description: 'The API client identifier provided to you by Medcrypt. KEEP THIS SECURE.'
    required: true
  client-secret:
    description: 'The API client secret provided to you by Medcrypt. KEEP THIS SECURE.'
    required: true
  workspace-name:
      description: 'The name of the workspace as it exists in the Helm system. CASE SENSITIVE. This is optional. If not provided, default workspace will be used.'
      required: false
  product-uuid:
    description: 'The 128-bit universally unique identifier for the product, such as 9ef5460a-5246-43dd-89cf-f98cfecaf46d. If this is not specified, then product-name must be provided'
    required: false
  product-name:
    description: 'The name of the product as it exists in the Helm system. CASE SENSITIVE. If this is not specified, then product-uuid must be provided.'
    required: false
  product-version-name:
    description:
      'The name of the product version as it exists in the Helm system. Not case sensitive. If this is a numeric value
      like 1.0, be sure to enclose it in quotes to prevent it from being treated as a number and possibly truncated.'
    required: true
  sbom-file-path:
    description: 'Path to the SBOM file within the github action workspace.'
    required: true
  create-product-if-not-found:
    description: 'If true, will create the product if it does not exist.'
    default: false
    required: false
  create-version-if-not-found:
    description: 'If true, will create the version of the product if it does not exist.'
    default: false
    required: false

runs:
  using: node20
  main: dist/index.js
