/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var heim_common_pb = require('../../heim_common_pb.js');
var v1_common_heim_enums_pb = require('../../v1/common/heim_enums_pb.js');
goog.exportSymbol('proto.medcrypt.helm.web.reports.GetReportFileRequest', null, global);
goog.exportSymbol('proto.medcrypt.helm.web.reports.GetReportRequestStateRequest', null, global);
goog.exportSymbol('proto.medcrypt.helm.web.reports.GetReportRequestStateResponse', null, global);
goog.exportSymbol('proto.medcrypt.helm.web.reports.RequestReportDataCycloneDxVex', null, global);
goog.exportSymbol('proto.medcrypt.helm.web.reports.RequestReportDataExecVulnSummary', null, global);
goog.exportSymbol('proto.medcrypt.helm.web.reports.RequestReportDataFda', null, global);
goog.exportSymbol('proto.medcrypt.helm.web.reports.RequestReportDataVulnCsv', null, global);
goog.exportSymbol('proto.medcrypt.helm.web.reports.RequestReportRequest', null, global);
goog.exportSymbol('proto.medcrypt.helm.web.reports.RequestReportResponse', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.medcrypt.helm.web.reports.RequestReportDataFda = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.medcrypt.helm.web.reports.RequestReportDataFda.repeatedFields_, null);
};
goog.inherits(proto.medcrypt.helm.web.reports.RequestReportDataFda, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.medcrypt.helm.web.reports.RequestReportDataFda.displayName = 'proto.medcrypt.helm.web.reports.RequestReportDataFda';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.medcrypt.helm.web.reports.RequestReportDataFda.repeatedFields_ = [5];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.medcrypt.helm.web.reports.RequestReportDataFda.prototype.toObject = function(opt_includeInstance) {
  return proto.medcrypt.helm.web.reports.RequestReportDataFda.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.medcrypt.helm.web.reports.RequestReportDataFda} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.medcrypt.helm.web.reports.RequestReportDataFda.toObject = function(includeInstance, msg) {
  var f, obj = {
    organizationProductVersionId: (f = msg.getOrganizationProductVersionId()) && heim_common_pb.UUID.toObject(includeInstance, f),
    includeSbomEntryReviewNotes: jspb.Message.getFieldWithDefault(msg, 2, false),
    includeCdxRemediation: jspb.Message.getFieldWithDefault(msg, 3, false),
    includeVexRemediation: jspb.Message.getFieldWithDefault(msg, 4, false),
    organizationProductVersionIdsList: jspb.Message.toObjectList(msg.getOrganizationProductVersionIdsList(),
    heim_common_pb.UUID.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.medcrypt.helm.web.reports.RequestReportDataFda}
 */
proto.medcrypt.helm.web.reports.RequestReportDataFda.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.medcrypt.helm.web.reports.RequestReportDataFda;
  return proto.medcrypt.helm.web.reports.RequestReportDataFda.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.medcrypt.helm.web.reports.RequestReportDataFda} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.medcrypt.helm.web.reports.RequestReportDataFda}
 */
proto.medcrypt.helm.web.reports.RequestReportDataFda.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new heim_common_pb.UUID;
      reader.readMessage(value,heim_common_pb.UUID.deserializeBinaryFromReader);
      msg.setOrganizationProductVersionId(value);
      break;
    case 2:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setIncludeSbomEntryReviewNotes(value);
      break;
    case 3:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setIncludeCdxRemediation(value);
      break;
    case 4:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setIncludeVexRemediation(value);
      break;
    case 5:
      var value = new heim_common_pb.UUID;
      reader.readMessage(value,heim_common_pb.UUID.deserializeBinaryFromReader);
      msg.addOrganizationProductVersionIds(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.medcrypt.helm.web.reports.RequestReportDataFda.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.medcrypt.helm.web.reports.RequestReportDataFda.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.medcrypt.helm.web.reports.RequestReportDataFda} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.medcrypt.helm.web.reports.RequestReportDataFda.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getOrganizationProductVersionId();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      heim_common_pb.UUID.serializeBinaryToWriter
    );
  }
  f = message.getIncludeSbomEntryReviewNotes();
  if (f) {
    writer.writeBool(
      2,
      f
    );
  }
  f = message.getIncludeCdxRemediation();
  if (f) {
    writer.writeBool(
      3,
      f
    );
  }
  f = message.getIncludeVexRemediation();
  if (f) {
    writer.writeBool(
      4,
      f
    );
  }
  f = message.getOrganizationProductVersionIdsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      5,
      f,
      heim_common_pb.UUID.serializeBinaryToWriter
    );
  }
};


/**
 * optional medcrypt.heimdall.web.common.UUID organization_product_version_id = 1;
 * @return {?proto.medcrypt.heimdall.web.common.UUID}
 */
proto.medcrypt.helm.web.reports.RequestReportDataFda.prototype.getOrganizationProductVersionId = function() {
  return /** @type{?proto.medcrypt.heimdall.web.common.UUID} */ (
    jspb.Message.getWrapperField(this, heim_common_pb.UUID, 1));
};


/** @param {?proto.medcrypt.heimdall.web.common.UUID|undefined} value */
proto.medcrypt.helm.web.reports.RequestReportDataFda.prototype.setOrganizationProductVersionId = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


proto.medcrypt.helm.web.reports.RequestReportDataFda.prototype.clearOrganizationProductVersionId = function() {
  this.setOrganizationProductVersionId(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.medcrypt.helm.web.reports.RequestReportDataFda.prototype.hasOrganizationProductVersionId = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional bool include_sbom_entry_review_notes = 2;
 * Note that Boolean fields may be set to 0/1 when serialized from a Java server.
 * You should avoid comparisons like {@code val === true/false} in those cases.
 * @return {boolean}
 */
proto.medcrypt.helm.web.reports.RequestReportDataFda.prototype.getIncludeSbomEntryReviewNotes = function() {
  return /** @type {boolean} */ (jspb.Message.getFieldWithDefault(this, 2, false));
};


/** @param {boolean} value */
proto.medcrypt.helm.web.reports.RequestReportDataFda.prototype.setIncludeSbomEntryReviewNotes = function(value) {
  jspb.Message.setProto3BooleanField(this, 2, value);
};


/**
 * optional bool include_cdx_remediation = 3;
 * Note that Boolean fields may be set to 0/1 when serialized from a Java server.
 * You should avoid comparisons like {@code val === true/false} in those cases.
 * @return {boolean}
 */
proto.medcrypt.helm.web.reports.RequestReportDataFda.prototype.getIncludeCdxRemediation = function() {
  return /** @type {boolean} */ (jspb.Message.getFieldWithDefault(this, 3, false));
};


/** @param {boolean} value */
proto.medcrypt.helm.web.reports.RequestReportDataFda.prototype.setIncludeCdxRemediation = function(value) {
  jspb.Message.setProto3BooleanField(this, 3, value);
};


/**
 * optional bool include_vex_remediation = 4;
 * Note that Boolean fields may be set to 0/1 when serialized from a Java server.
 * You should avoid comparisons like {@code val === true/false} in those cases.
 * @return {boolean}
 */
proto.medcrypt.helm.web.reports.RequestReportDataFda.prototype.getIncludeVexRemediation = function() {
  return /** @type {boolean} */ (jspb.Message.getFieldWithDefault(this, 4, false));
};


/** @param {boolean} value */
proto.medcrypt.helm.web.reports.RequestReportDataFda.prototype.setIncludeVexRemediation = function(value) {
  jspb.Message.setProto3BooleanField(this, 4, value);
};


/**
 * repeated medcrypt.heimdall.web.common.UUID organization_product_version_ids = 5;
 * @return {!Array.<!proto.medcrypt.heimdall.web.common.UUID>}
 */
proto.medcrypt.helm.web.reports.RequestReportDataFda.prototype.getOrganizationProductVersionIdsList = function() {
  return /** @type{!Array.<!proto.medcrypt.heimdall.web.common.UUID>} */ (
    jspb.Message.getRepeatedWrapperField(this, heim_common_pb.UUID, 5));
};


/** @param {!Array.<!proto.medcrypt.heimdall.web.common.UUID>} value */
proto.medcrypt.helm.web.reports.RequestReportDataFda.prototype.setOrganizationProductVersionIdsList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 5, value);
};


/**
 * @param {!proto.medcrypt.heimdall.web.common.UUID=} opt_value
 * @param {number=} opt_index
 * @return {!proto.medcrypt.heimdall.web.common.UUID}
 */
proto.medcrypt.helm.web.reports.RequestReportDataFda.prototype.addOrganizationProductVersionIds = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 5, opt_value, proto.medcrypt.heimdall.web.common.UUID, opt_index);
};


proto.medcrypt.helm.web.reports.RequestReportDataFda.prototype.clearOrganizationProductVersionIdsList = function() {
  this.setOrganizationProductVersionIdsList([]);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.medcrypt.helm.web.reports.RequestReportDataCycloneDxVex = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.medcrypt.helm.web.reports.RequestReportDataCycloneDxVex.repeatedFields_, null);
};
goog.inherits(proto.medcrypt.helm.web.reports.RequestReportDataCycloneDxVex, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.medcrypt.helm.web.reports.RequestReportDataCycloneDxVex.displayName = 'proto.medcrypt.helm.web.reports.RequestReportDataCycloneDxVex';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.medcrypt.helm.web.reports.RequestReportDataCycloneDxVex.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.medcrypt.helm.web.reports.RequestReportDataCycloneDxVex.prototype.toObject = function(opt_includeInstance) {
  return proto.medcrypt.helm.web.reports.RequestReportDataCycloneDxVex.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.medcrypt.helm.web.reports.RequestReportDataCycloneDxVex} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.medcrypt.helm.web.reports.RequestReportDataCycloneDxVex.toObject = function(includeInstance, msg) {
  var f, obj = {
    organizationProductVersionId: (f = msg.getOrganizationProductVersionId()) && heim_common_pb.UUID.toObject(includeInstance, f),
    organizationProductVersionIdsList: jspb.Message.toObjectList(msg.getOrganizationProductVersionIdsList(),
    heim_common_pb.UUID.toObject, includeInstance),
    uniqueCdxVexReportId: jspb.Message.getFieldWithDefault(msg, 3, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.medcrypt.helm.web.reports.RequestReportDataCycloneDxVex}
 */
proto.medcrypt.helm.web.reports.RequestReportDataCycloneDxVex.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.medcrypt.helm.web.reports.RequestReportDataCycloneDxVex;
  return proto.medcrypt.helm.web.reports.RequestReportDataCycloneDxVex.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.medcrypt.helm.web.reports.RequestReportDataCycloneDxVex} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.medcrypt.helm.web.reports.RequestReportDataCycloneDxVex}
 */
proto.medcrypt.helm.web.reports.RequestReportDataCycloneDxVex.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new heim_common_pb.UUID;
      reader.readMessage(value,heim_common_pb.UUID.deserializeBinaryFromReader);
      msg.setOrganizationProductVersionId(value);
      break;
    case 2:
      var value = new heim_common_pb.UUID;
      reader.readMessage(value,heim_common_pb.UUID.deserializeBinaryFromReader);
      msg.addOrganizationProductVersionIds(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setUniqueCdxVexReportId(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.medcrypt.helm.web.reports.RequestReportDataCycloneDxVex.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.medcrypt.helm.web.reports.RequestReportDataCycloneDxVex.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.medcrypt.helm.web.reports.RequestReportDataCycloneDxVex} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.medcrypt.helm.web.reports.RequestReportDataCycloneDxVex.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getOrganizationProductVersionId();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      heim_common_pb.UUID.serializeBinaryToWriter
    );
  }
  f = message.getOrganizationProductVersionIdsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      heim_common_pb.UUID.serializeBinaryToWriter
    );
  }
  f = message.getUniqueCdxVexReportId();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
};


/**
 * optional medcrypt.heimdall.web.common.UUID organization_product_version_id = 1;
 * @return {?proto.medcrypt.heimdall.web.common.UUID}
 */
proto.medcrypt.helm.web.reports.RequestReportDataCycloneDxVex.prototype.getOrganizationProductVersionId = function() {
  return /** @type{?proto.medcrypt.heimdall.web.common.UUID} */ (
    jspb.Message.getWrapperField(this, heim_common_pb.UUID, 1));
};


/** @param {?proto.medcrypt.heimdall.web.common.UUID|undefined} value */
proto.medcrypt.helm.web.reports.RequestReportDataCycloneDxVex.prototype.setOrganizationProductVersionId = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


proto.medcrypt.helm.web.reports.RequestReportDataCycloneDxVex.prototype.clearOrganizationProductVersionId = function() {
  this.setOrganizationProductVersionId(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.medcrypt.helm.web.reports.RequestReportDataCycloneDxVex.prototype.hasOrganizationProductVersionId = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * repeated medcrypt.heimdall.web.common.UUID organization_product_version_ids = 2;
 * @return {!Array.<!proto.medcrypt.heimdall.web.common.UUID>}
 */
proto.medcrypt.helm.web.reports.RequestReportDataCycloneDxVex.prototype.getOrganizationProductVersionIdsList = function() {
  return /** @type{!Array.<!proto.medcrypt.heimdall.web.common.UUID>} */ (
    jspb.Message.getRepeatedWrapperField(this, heim_common_pb.UUID, 2));
};


/** @param {!Array.<!proto.medcrypt.heimdall.web.common.UUID>} value */
proto.medcrypt.helm.web.reports.RequestReportDataCycloneDxVex.prototype.setOrganizationProductVersionIdsList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.medcrypt.heimdall.web.common.UUID=} opt_value
 * @param {number=} opt_index
 * @return {!proto.medcrypt.heimdall.web.common.UUID}
 */
proto.medcrypt.helm.web.reports.RequestReportDataCycloneDxVex.prototype.addOrganizationProductVersionIds = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.medcrypt.heimdall.web.common.UUID, opt_index);
};


proto.medcrypt.helm.web.reports.RequestReportDataCycloneDxVex.prototype.clearOrganizationProductVersionIdsList = function() {
  this.setOrganizationProductVersionIdsList([]);
};


/**
 * optional string unique_cdx_vex_report_id = 3;
 * @return {string}
 */
proto.medcrypt.helm.web.reports.RequestReportDataCycloneDxVex.prototype.getUniqueCdxVexReportId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/** @param {string} value */
proto.medcrypt.helm.web.reports.RequestReportDataCycloneDxVex.prototype.setUniqueCdxVexReportId = function(value) {
  jspb.Message.setProto3StringField(this, 3, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.medcrypt.helm.web.reports.RequestReportDataVulnCsv = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.medcrypt.helm.web.reports.RequestReportDataVulnCsv.repeatedFields_, null);
};
goog.inherits(proto.medcrypt.helm.web.reports.RequestReportDataVulnCsv, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.medcrypt.helm.web.reports.RequestReportDataVulnCsv.displayName = 'proto.medcrypt.helm.web.reports.RequestReportDataVulnCsv';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.medcrypt.helm.web.reports.RequestReportDataVulnCsv.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.medcrypt.helm.web.reports.RequestReportDataVulnCsv.prototype.toObject = function(opt_includeInstance) {
  return proto.medcrypt.helm.web.reports.RequestReportDataVulnCsv.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.medcrypt.helm.web.reports.RequestReportDataVulnCsv} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.medcrypt.helm.web.reports.RequestReportDataVulnCsv.toObject = function(includeInstance, msg) {
  var f, obj = {
    organizationProductVersionIdsList: jspb.Message.toObjectList(msg.getOrganizationProductVersionIdsList(),
    heim_common_pb.UUID.toObject, includeInstance),
    page: (f = msg.getPage()) && heim_common_pb.Page.toObject(includeInstance, f),
    includeSummaries: jspb.Message.getFieldWithDefault(msg, 5, false)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.medcrypt.helm.web.reports.RequestReportDataVulnCsv}
 */
proto.medcrypt.helm.web.reports.RequestReportDataVulnCsv.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.medcrypt.helm.web.reports.RequestReportDataVulnCsv;
  return proto.medcrypt.helm.web.reports.RequestReportDataVulnCsv.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.medcrypt.helm.web.reports.RequestReportDataVulnCsv} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.medcrypt.helm.web.reports.RequestReportDataVulnCsv}
 */
proto.medcrypt.helm.web.reports.RequestReportDataVulnCsv.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new heim_common_pb.UUID;
      reader.readMessage(value,heim_common_pb.UUID.deserializeBinaryFromReader);
      msg.addOrganizationProductVersionIds(value);
      break;
    case 2:
      var value = new heim_common_pb.Page;
      reader.readMessage(value,heim_common_pb.Page.deserializeBinaryFromReader);
      msg.setPage(value);
      break;
    case 5:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setIncludeSummaries(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.medcrypt.helm.web.reports.RequestReportDataVulnCsv.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.medcrypt.helm.web.reports.RequestReportDataVulnCsv.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.medcrypt.helm.web.reports.RequestReportDataVulnCsv} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.medcrypt.helm.web.reports.RequestReportDataVulnCsv.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getOrganizationProductVersionIdsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      heim_common_pb.UUID.serializeBinaryToWriter
    );
  }
  f = message.getPage();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      heim_common_pb.Page.serializeBinaryToWriter
    );
  }
  f = message.getIncludeSummaries();
  if (f) {
    writer.writeBool(
      5,
      f
    );
  }
};


/**
 * repeated medcrypt.heimdall.web.common.UUID organization_product_version_ids = 1;
 * @return {!Array.<!proto.medcrypt.heimdall.web.common.UUID>}
 */
proto.medcrypt.helm.web.reports.RequestReportDataVulnCsv.prototype.getOrganizationProductVersionIdsList = function() {
  return /** @type{!Array.<!proto.medcrypt.heimdall.web.common.UUID>} */ (
    jspb.Message.getRepeatedWrapperField(this, heim_common_pb.UUID, 1));
};


/** @param {!Array.<!proto.medcrypt.heimdall.web.common.UUID>} value */
proto.medcrypt.helm.web.reports.RequestReportDataVulnCsv.prototype.setOrganizationProductVersionIdsList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.medcrypt.heimdall.web.common.UUID=} opt_value
 * @param {number=} opt_index
 * @return {!proto.medcrypt.heimdall.web.common.UUID}
 */
proto.medcrypt.helm.web.reports.RequestReportDataVulnCsv.prototype.addOrganizationProductVersionIds = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.medcrypt.heimdall.web.common.UUID, opt_index);
};


proto.medcrypt.helm.web.reports.RequestReportDataVulnCsv.prototype.clearOrganizationProductVersionIdsList = function() {
  this.setOrganizationProductVersionIdsList([]);
};


/**
 * optional medcrypt.heimdall.web.common.Page page = 2;
 * @return {?proto.medcrypt.heimdall.web.common.Page}
 */
proto.medcrypt.helm.web.reports.RequestReportDataVulnCsv.prototype.getPage = function() {
  return /** @type{?proto.medcrypt.heimdall.web.common.Page} */ (
    jspb.Message.getWrapperField(this, heim_common_pb.Page, 2));
};


/** @param {?proto.medcrypt.heimdall.web.common.Page|undefined} value */
proto.medcrypt.helm.web.reports.RequestReportDataVulnCsv.prototype.setPage = function(value) {
  jspb.Message.setWrapperField(this, 2, value);
};


proto.medcrypt.helm.web.reports.RequestReportDataVulnCsv.prototype.clearPage = function() {
  this.setPage(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.medcrypt.helm.web.reports.RequestReportDataVulnCsv.prototype.hasPage = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional bool include_summaries = 5;
 * Note that Boolean fields may be set to 0/1 when serialized from a Java server.
 * You should avoid comparisons like {@code val === true/false} in those cases.
 * @return {boolean}
 */
proto.medcrypt.helm.web.reports.RequestReportDataVulnCsv.prototype.getIncludeSummaries = function() {
  return /** @type {boolean} */ (jspb.Message.getFieldWithDefault(this, 5, false));
};


/** @param {boolean} value */
proto.medcrypt.helm.web.reports.RequestReportDataVulnCsv.prototype.setIncludeSummaries = function(value) {
  jspb.Message.setProto3BooleanField(this, 5, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.medcrypt.helm.web.reports.RequestReportDataExecVulnSummary = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.medcrypt.helm.web.reports.RequestReportDataExecVulnSummary, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.medcrypt.helm.web.reports.RequestReportDataExecVulnSummary.displayName = 'proto.medcrypt.helm.web.reports.RequestReportDataExecVulnSummary';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.medcrypt.helm.web.reports.RequestReportDataExecVulnSummary.prototype.toObject = function(opt_includeInstance) {
  return proto.medcrypt.helm.web.reports.RequestReportDataExecVulnSummary.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.medcrypt.helm.web.reports.RequestReportDataExecVulnSummary} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.medcrypt.helm.web.reports.RequestReportDataExecVulnSummary.toObject = function(includeInstance, msg) {
  var f, obj = {
    orgProductVersionId: (f = msg.getOrgProductVersionId()) && heim_common_pb.UUID.toObject(includeInstance, f),
    llmDownloadToken: jspb.Message.getFieldWithDefault(msg, 2, ""),
    emailRecipients: jspb.Message.getFieldWithDefault(msg, 3, ""),
    workspaceUuid: (f = msg.getWorkspaceUuid()) && heim_common_pb.UUID.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.medcrypt.helm.web.reports.RequestReportDataExecVulnSummary}
 */
proto.medcrypt.helm.web.reports.RequestReportDataExecVulnSummary.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.medcrypt.helm.web.reports.RequestReportDataExecVulnSummary;
  return proto.medcrypt.helm.web.reports.RequestReportDataExecVulnSummary.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.medcrypt.helm.web.reports.RequestReportDataExecVulnSummary} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.medcrypt.helm.web.reports.RequestReportDataExecVulnSummary}
 */
proto.medcrypt.helm.web.reports.RequestReportDataExecVulnSummary.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new heim_common_pb.UUID;
      reader.readMessage(value,heim_common_pb.UUID.deserializeBinaryFromReader);
      msg.setOrgProductVersionId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setLlmDownloadToken(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setEmailRecipients(value);
      break;
    case 4:
      var value = new heim_common_pb.UUID;
      reader.readMessage(value,heim_common_pb.UUID.deserializeBinaryFromReader);
      msg.setWorkspaceUuid(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.medcrypt.helm.web.reports.RequestReportDataExecVulnSummary.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.medcrypt.helm.web.reports.RequestReportDataExecVulnSummary.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.medcrypt.helm.web.reports.RequestReportDataExecVulnSummary} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.medcrypt.helm.web.reports.RequestReportDataExecVulnSummary.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getOrgProductVersionId();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      heim_common_pb.UUID.serializeBinaryToWriter
    );
  }
  f = message.getLlmDownloadToken();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getEmailRecipients();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getWorkspaceUuid();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      heim_common_pb.UUID.serializeBinaryToWriter
    );
  }
};


/**
 * optional medcrypt.heimdall.web.common.UUID org_product_version_id = 1;
 * @return {?proto.medcrypt.heimdall.web.common.UUID}
 */
proto.medcrypt.helm.web.reports.RequestReportDataExecVulnSummary.prototype.getOrgProductVersionId = function() {
  return /** @type{?proto.medcrypt.heimdall.web.common.UUID} */ (
    jspb.Message.getWrapperField(this, heim_common_pb.UUID, 1));
};


/** @param {?proto.medcrypt.heimdall.web.common.UUID|undefined} value */
proto.medcrypt.helm.web.reports.RequestReportDataExecVulnSummary.prototype.setOrgProductVersionId = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


proto.medcrypt.helm.web.reports.RequestReportDataExecVulnSummary.prototype.clearOrgProductVersionId = function() {
  this.setOrgProductVersionId(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.medcrypt.helm.web.reports.RequestReportDataExecVulnSummary.prototype.hasOrgProductVersionId = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional string llm_download_token = 2;
 * @return {string}
 */
proto.medcrypt.helm.web.reports.RequestReportDataExecVulnSummary.prototype.getLlmDownloadToken = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.medcrypt.helm.web.reports.RequestReportDataExecVulnSummary.prototype.setLlmDownloadToken = function(value) {
  jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string email_recipients = 3;
 * @return {string}
 */
proto.medcrypt.helm.web.reports.RequestReportDataExecVulnSummary.prototype.getEmailRecipients = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/** @param {string} value */
proto.medcrypt.helm.web.reports.RequestReportDataExecVulnSummary.prototype.setEmailRecipients = function(value) {
  jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional medcrypt.heimdall.web.common.UUID workspace_uuid = 4;
 * @return {?proto.medcrypt.heimdall.web.common.UUID}
 */
proto.medcrypt.helm.web.reports.RequestReportDataExecVulnSummary.prototype.getWorkspaceUuid = function() {
  return /** @type{?proto.medcrypt.heimdall.web.common.UUID} */ (
    jspb.Message.getWrapperField(this, heim_common_pb.UUID, 4));
};


/** @param {?proto.medcrypt.heimdall.web.common.UUID|undefined} value */
proto.medcrypt.helm.web.reports.RequestReportDataExecVulnSummary.prototype.setWorkspaceUuid = function(value) {
  jspb.Message.setWrapperField(this, 4, value);
};


proto.medcrypt.helm.web.reports.RequestReportDataExecVulnSummary.prototype.clearWorkspaceUuid = function() {
  this.setWorkspaceUuid(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.medcrypt.helm.web.reports.RequestReportDataExecVulnSummary.prototype.hasWorkspaceUuid = function() {
  return jspb.Message.getField(this, 4) != null;
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.medcrypt.helm.web.reports.RequestReportRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.medcrypt.helm.web.reports.RequestReportRequest.oneofGroups_);
};
goog.inherits(proto.medcrypt.helm.web.reports.RequestReportRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.medcrypt.helm.web.reports.RequestReportRequest.displayName = 'proto.medcrypt.helm.web.reports.RequestReportRequest';
}
/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.medcrypt.helm.web.reports.RequestReportRequest.oneofGroups_ = [[2,3,4,5]];

/**
 * @enum {number}
 */
proto.medcrypt.helm.web.reports.RequestReportRequest.ReportdataCase = {
  REPORTDATA_NOT_SET: 0,
  REPORT_REQUEST_DATA_FDA: 2,
  REPORT_REQUEST_DATA_CYCLONE_DX_VEX: 3,
  REPORT_REQUEST_DATA_VULN_CSV: 4,
  REPORT_REQUEST_EXEC_VULN_SUMMARY: 5
};

/**
 * @return {proto.medcrypt.helm.web.reports.RequestReportRequest.ReportdataCase}
 */
proto.medcrypt.helm.web.reports.RequestReportRequest.prototype.getReportdataCase = function() {
  return /** @type {proto.medcrypt.helm.web.reports.RequestReportRequest.ReportdataCase} */(jspb.Message.computeOneofCase(this, proto.medcrypt.helm.web.reports.RequestReportRequest.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.medcrypt.helm.web.reports.RequestReportRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.medcrypt.helm.web.reports.RequestReportRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.medcrypt.helm.web.reports.RequestReportRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.medcrypt.helm.web.reports.RequestReportRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    metadata: (f = msg.getMetadata()) && heim_common_pb.RequestMetadata.toObject(includeInstance, f),
    reportRequestDataFda: (f = msg.getReportRequestDataFda()) && proto.medcrypt.helm.web.reports.RequestReportDataFda.toObject(includeInstance, f),
    reportRequestDataCycloneDxVex: (f = msg.getReportRequestDataCycloneDxVex()) && proto.medcrypt.helm.web.reports.RequestReportDataCycloneDxVex.toObject(includeInstance, f),
    reportRequestDataVulnCsv: (f = msg.getReportRequestDataVulnCsv()) && proto.medcrypt.helm.web.reports.RequestReportDataVulnCsv.toObject(includeInstance, f),
    reportRequestExecVulnSummary: (f = msg.getReportRequestExecVulnSummary()) && proto.medcrypt.helm.web.reports.RequestReportDataExecVulnSummary.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.medcrypt.helm.web.reports.RequestReportRequest}
 */
proto.medcrypt.helm.web.reports.RequestReportRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.medcrypt.helm.web.reports.RequestReportRequest;
  return proto.medcrypt.helm.web.reports.RequestReportRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.medcrypt.helm.web.reports.RequestReportRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.medcrypt.helm.web.reports.RequestReportRequest}
 */
proto.medcrypt.helm.web.reports.RequestReportRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new heim_common_pb.RequestMetadata;
      reader.readMessage(value,heim_common_pb.RequestMetadata.deserializeBinaryFromReader);
      msg.setMetadata(value);
      break;
    case 2:
      var value = new proto.medcrypt.helm.web.reports.RequestReportDataFda;
      reader.readMessage(value,proto.medcrypt.helm.web.reports.RequestReportDataFda.deserializeBinaryFromReader);
      msg.setReportRequestDataFda(value);
      break;
    case 3:
      var value = new proto.medcrypt.helm.web.reports.RequestReportDataCycloneDxVex;
      reader.readMessage(value,proto.medcrypt.helm.web.reports.RequestReportDataCycloneDxVex.deserializeBinaryFromReader);
      msg.setReportRequestDataCycloneDxVex(value);
      break;
    case 4:
      var value = new proto.medcrypt.helm.web.reports.RequestReportDataVulnCsv;
      reader.readMessage(value,proto.medcrypt.helm.web.reports.RequestReportDataVulnCsv.deserializeBinaryFromReader);
      msg.setReportRequestDataVulnCsv(value);
      break;
    case 5:
      var value = new proto.medcrypt.helm.web.reports.RequestReportDataExecVulnSummary;
      reader.readMessage(value,proto.medcrypt.helm.web.reports.RequestReportDataExecVulnSummary.deserializeBinaryFromReader);
      msg.setReportRequestExecVulnSummary(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.medcrypt.helm.web.reports.RequestReportRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.medcrypt.helm.web.reports.RequestReportRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.medcrypt.helm.web.reports.RequestReportRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.medcrypt.helm.web.reports.RequestReportRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getMetadata();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      heim_common_pb.RequestMetadata.serializeBinaryToWriter
    );
  }
  f = message.getReportRequestDataFda();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.medcrypt.helm.web.reports.RequestReportDataFda.serializeBinaryToWriter
    );
  }
  f = message.getReportRequestDataCycloneDxVex();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.medcrypt.helm.web.reports.RequestReportDataCycloneDxVex.serializeBinaryToWriter
    );
  }
  f = message.getReportRequestDataVulnCsv();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      proto.medcrypt.helm.web.reports.RequestReportDataVulnCsv.serializeBinaryToWriter
    );
  }
  f = message.getReportRequestExecVulnSummary();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      proto.medcrypt.helm.web.reports.RequestReportDataExecVulnSummary.serializeBinaryToWriter
    );
  }
};


/**
 * optional medcrypt.heimdall.web.common.RequestMetadata metadata = 1;
 * @return {?proto.medcrypt.heimdall.web.common.RequestMetadata}
 */
proto.medcrypt.helm.web.reports.RequestReportRequest.prototype.getMetadata = function() {
  return /** @type{?proto.medcrypt.heimdall.web.common.RequestMetadata} */ (
    jspb.Message.getWrapperField(this, heim_common_pb.RequestMetadata, 1));
};


/** @param {?proto.medcrypt.heimdall.web.common.RequestMetadata|undefined} value */
proto.medcrypt.helm.web.reports.RequestReportRequest.prototype.setMetadata = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


proto.medcrypt.helm.web.reports.RequestReportRequest.prototype.clearMetadata = function() {
  this.setMetadata(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.medcrypt.helm.web.reports.RequestReportRequest.prototype.hasMetadata = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional RequestReportDataFda report_request_data_fda = 2;
 * @return {?proto.medcrypt.helm.web.reports.RequestReportDataFda}
 */
proto.medcrypt.helm.web.reports.RequestReportRequest.prototype.getReportRequestDataFda = function() {
  return /** @type{?proto.medcrypt.helm.web.reports.RequestReportDataFda} */ (
    jspb.Message.getWrapperField(this, proto.medcrypt.helm.web.reports.RequestReportDataFda, 2));
};


/** @param {?proto.medcrypt.helm.web.reports.RequestReportDataFda|undefined} value */
proto.medcrypt.helm.web.reports.RequestReportRequest.prototype.setReportRequestDataFda = function(value) {
  jspb.Message.setOneofWrapperField(this, 2, proto.medcrypt.helm.web.reports.RequestReportRequest.oneofGroups_[0], value);
};


proto.medcrypt.helm.web.reports.RequestReportRequest.prototype.clearReportRequestDataFda = function() {
  this.setReportRequestDataFda(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.medcrypt.helm.web.reports.RequestReportRequest.prototype.hasReportRequestDataFda = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional RequestReportDataCycloneDxVex report_request_data_cyclone_dx_vex = 3;
 * @return {?proto.medcrypt.helm.web.reports.RequestReportDataCycloneDxVex}
 */
proto.medcrypt.helm.web.reports.RequestReportRequest.prototype.getReportRequestDataCycloneDxVex = function() {
  return /** @type{?proto.medcrypt.helm.web.reports.RequestReportDataCycloneDxVex} */ (
    jspb.Message.getWrapperField(this, proto.medcrypt.helm.web.reports.RequestReportDataCycloneDxVex, 3));
};


/** @param {?proto.medcrypt.helm.web.reports.RequestReportDataCycloneDxVex|undefined} value */
proto.medcrypt.helm.web.reports.RequestReportRequest.prototype.setReportRequestDataCycloneDxVex = function(value) {
  jspb.Message.setOneofWrapperField(this, 3, proto.medcrypt.helm.web.reports.RequestReportRequest.oneofGroups_[0], value);
};


proto.medcrypt.helm.web.reports.RequestReportRequest.prototype.clearReportRequestDataCycloneDxVex = function() {
  this.setReportRequestDataCycloneDxVex(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.medcrypt.helm.web.reports.RequestReportRequest.prototype.hasReportRequestDataCycloneDxVex = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional RequestReportDataVulnCsv report_request_data_vuln_csv = 4;
 * @return {?proto.medcrypt.helm.web.reports.RequestReportDataVulnCsv}
 */
proto.medcrypt.helm.web.reports.RequestReportRequest.prototype.getReportRequestDataVulnCsv = function() {
  return /** @type{?proto.medcrypt.helm.web.reports.RequestReportDataVulnCsv} */ (
    jspb.Message.getWrapperField(this, proto.medcrypt.helm.web.reports.RequestReportDataVulnCsv, 4));
};


/** @param {?proto.medcrypt.helm.web.reports.RequestReportDataVulnCsv|undefined} value */
proto.medcrypt.helm.web.reports.RequestReportRequest.prototype.setReportRequestDataVulnCsv = function(value) {
  jspb.Message.setOneofWrapperField(this, 4, proto.medcrypt.helm.web.reports.RequestReportRequest.oneofGroups_[0], value);
};


proto.medcrypt.helm.web.reports.RequestReportRequest.prototype.clearReportRequestDataVulnCsv = function() {
  this.setReportRequestDataVulnCsv(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.medcrypt.helm.web.reports.RequestReportRequest.prototype.hasReportRequestDataVulnCsv = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional RequestReportDataExecVulnSummary report_request_exec_vuln_summary = 5;
 * @return {?proto.medcrypt.helm.web.reports.RequestReportDataExecVulnSummary}
 */
proto.medcrypt.helm.web.reports.RequestReportRequest.prototype.getReportRequestExecVulnSummary = function() {
  return /** @type{?proto.medcrypt.helm.web.reports.RequestReportDataExecVulnSummary} */ (
    jspb.Message.getWrapperField(this, proto.medcrypt.helm.web.reports.RequestReportDataExecVulnSummary, 5));
};


/** @param {?proto.medcrypt.helm.web.reports.RequestReportDataExecVulnSummary|undefined} value */
proto.medcrypt.helm.web.reports.RequestReportRequest.prototype.setReportRequestExecVulnSummary = function(value) {
  jspb.Message.setOneofWrapperField(this, 5, proto.medcrypt.helm.web.reports.RequestReportRequest.oneofGroups_[0], value);
};


proto.medcrypt.helm.web.reports.RequestReportRequest.prototype.clearReportRequestExecVulnSummary = function() {
  this.setReportRequestExecVulnSummary(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.medcrypt.helm.web.reports.RequestReportRequest.prototype.hasReportRequestExecVulnSummary = function() {
  return jspb.Message.getField(this, 5) != null;
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.medcrypt.helm.web.reports.RequestReportResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.medcrypt.helm.web.reports.RequestReportResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.medcrypt.helm.web.reports.RequestReportResponse.displayName = 'proto.medcrypt.helm.web.reports.RequestReportResponse';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.medcrypt.helm.web.reports.RequestReportResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.medcrypt.helm.web.reports.RequestReportResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.medcrypt.helm.web.reports.RequestReportResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.medcrypt.helm.web.reports.RequestReportResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    metadata: (f = msg.getMetadata()) && heim_common_pb.ResponseMetadata.toObject(includeInstance, f),
    reportRequestId: (f = msg.getReportRequestId()) && heim_common_pb.UUID.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.medcrypt.helm.web.reports.RequestReportResponse}
 */
proto.medcrypt.helm.web.reports.RequestReportResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.medcrypt.helm.web.reports.RequestReportResponse;
  return proto.medcrypt.helm.web.reports.RequestReportResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.medcrypt.helm.web.reports.RequestReportResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.medcrypt.helm.web.reports.RequestReportResponse}
 */
proto.medcrypt.helm.web.reports.RequestReportResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new heim_common_pb.ResponseMetadata;
      reader.readMessage(value,heim_common_pb.ResponseMetadata.deserializeBinaryFromReader);
      msg.setMetadata(value);
      break;
    case 2:
      var value = new heim_common_pb.UUID;
      reader.readMessage(value,heim_common_pb.UUID.deserializeBinaryFromReader);
      msg.setReportRequestId(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.medcrypt.helm.web.reports.RequestReportResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.medcrypt.helm.web.reports.RequestReportResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.medcrypt.helm.web.reports.RequestReportResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.medcrypt.helm.web.reports.RequestReportResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getMetadata();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      heim_common_pb.ResponseMetadata.serializeBinaryToWriter
    );
  }
  f = message.getReportRequestId();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      heim_common_pb.UUID.serializeBinaryToWriter
    );
  }
};


/**
 * optional medcrypt.heimdall.web.common.ResponseMetadata metadata = 1;
 * @return {?proto.medcrypt.heimdall.web.common.ResponseMetadata}
 */
proto.medcrypt.helm.web.reports.RequestReportResponse.prototype.getMetadata = function() {
  return /** @type{?proto.medcrypt.heimdall.web.common.ResponseMetadata} */ (
    jspb.Message.getWrapperField(this, heim_common_pb.ResponseMetadata, 1));
};


/** @param {?proto.medcrypt.heimdall.web.common.ResponseMetadata|undefined} value */
proto.medcrypt.helm.web.reports.RequestReportResponse.prototype.setMetadata = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


proto.medcrypt.helm.web.reports.RequestReportResponse.prototype.clearMetadata = function() {
  this.setMetadata(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.medcrypt.helm.web.reports.RequestReportResponse.prototype.hasMetadata = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional medcrypt.heimdall.web.common.UUID report_request_id = 2;
 * @return {?proto.medcrypt.heimdall.web.common.UUID}
 */
proto.medcrypt.helm.web.reports.RequestReportResponse.prototype.getReportRequestId = function() {
  return /** @type{?proto.medcrypt.heimdall.web.common.UUID} */ (
    jspb.Message.getWrapperField(this, heim_common_pb.UUID, 2));
};


/** @param {?proto.medcrypt.heimdall.web.common.UUID|undefined} value */
proto.medcrypt.helm.web.reports.RequestReportResponse.prototype.setReportRequestId = function(value) {
  jspb.Message.setWrapperField(this, 2, value);
};


proto.medcrypt.helm.web.reports.RequestReportResponse.prototype.clearReportRequestId = function() {
  this.setReportRequestId(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.medcrypt.helm.web.reports.RequestReportResponse.prototype.hasReportRequestId = function() {
  return jspb.Message.getField(this, 2) != null;
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.medcrypt.helm.web.reports.GetReportRequestStateRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.medcrypt.helm.web.reports.GetReportRequestStateRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.medcrypt.helm.web.reports.GetReportRequestStateRequest.displayName = 'proto.medcrypt.helm.web.reports.GetReportRequestStateRequest';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.medcrypt.helm.web.reports.GetReportRequestStateRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.medcrypt.helm.web.reports.GetReportRequestStateRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.medcrypt.helm.web.reports.GetReportRequestStateRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.medcrypt.helm.web.reports.GetReportRequestStateRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    metadata: (f = msg.getMetadata()) && heim_common_pb.RequestMetadata.toObject(includeInstance, f),
    reportRequestId: (f = msg.getReportRequestId()) && heim_common_pb.UUID.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.medcrypt.helm.web.reports.GetReportRequestStateRequest}
 */
proto.medcrypt.helm.web.reports.GetReportRequestStateRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.medcrypt.helm.web.reports.GetReportRequestStateRequest;
  return proto.medcrypt.helm.web.reports.GetReportRequestStateRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.medcrypt.helm.web.reports.GetReportRequestStateRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.medcrypt.helm.web.reports.GetReportRequestStateRequest}
 */
proto.medcrypt.helm.web.reports.GetReportRequestStateRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new heim_common_pb.RequestMetadata;
      reader.readMessage(value,heim_common_pb.RequestMetadata.deserializeBinaryFromReader);
      msg.setMetadata(value);
      break;
    case 2:
      var value = new heim_common_pb.UUID;
      reader.readMessage(value,heim_common_pb.UUID.deserializeBinaryFromReader);
      msg.setReportRequestId(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.medcrypt.helm.web.reports.GetReportRequestStateRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.medcrypt.helm.web.reports.GetReportRequestStateRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.medcrypt.helm.web.reports.GetReportRequestStateRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.medcrypt.helm.web.reports.GetReportRequestStateRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getMetadata();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      heim_common_pb.RequestMetadata.serializeBinaryToWriter
    );
  }
  f = message.getReportRequestId();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      heim_common_pb.UUID.serializeBinaryToWriter
    );
  }
};


/**
 * optional medcrypt.heimdall.web.common.RequestMetadata metadata = 1;
 * @return {?proto.medcrypt.heimdall.web.common.RequestMetadata}
 */
proto.medcrypt.helm.web.reports.GetReportRequestStateRequest.prototype.getMetadata = function() {
  return /** @type{?proto.medcrypt.heimdall.web.common.RequestMetadata} */ (
    jspb.Message.getWrapperField(this, heim_common_pb.RequestMetadata, 1));
};


/** @param {?proto.medcrypt.heimdall.web.common.RequestMetadata|undefined} value */
proto.medcrypt.helm.web.reports.GetReportRequestStateRequest.prototype.setMetadata = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


proto.medcrypt.helm.web.reports.GetReportRequestStateRequest.prototype.clearMetadata = function() {
  this.setMetadata(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.medcrypt.helm.web.reports.GetReportRequestStateRequest.prototype.hasMetadata = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional medcrypt.heimdall.web.common.UUID report_request_id = 2;
 * @return {?proto.medcrypt.heimdall.web.common.UUID}
 */
proto.medcrypt.helm.web.reports.GetReportRequestStateRequest.prototype.getReportRequestId = function() {
  return /** @type{?proto.medcrypt.heimdall.web.common.UUID} */ (
    jspb.Message.getWrapperField(this, heim_common_pb.UUID, 2));
};


/** @param {?proto.medcrypt.heimdall.web.common.UUID|undefined} value */
proto.medcrypt.helm.web.reports.GetReportRequestStateRequest.prototype.setReportRequestId = function(value) {
  jspb.Message.setWrapperField(this, 2, value);
};


proto.medcrypt.helm.web.reports.GetReportRequestStateRequest.prototype.clearReportRequestId = function() {
  this.setReportRequestId(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.medcrypt.helm.web.reports.GetReportRequestStateRequest.prototype.hasReportRequestId = function() {
  return jspb.Message.getField(this, 2) != null;
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.medcrypt.helm.web.reports.GetReportRequestStateResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.medcrypt.helm.web.reports.GetReportRequestStateResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.medcrypt.helm.web.reports.GetReportRequestStateResponse.displayName = 'proto.medcrypt.helm.web.reports.GetReportRequestStateResponse';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.medcrypt.helm.web.reports.GetReportRequestStateResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.medcrypt.helm.web.reports.GetReportRequestStateResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.medcrypt.helm.web.reports.GetReportRequestStateResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.medcrypt.helm.web.reports.GetReportRequestStateResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    metadata: (f = msg.getMetadata()) && heim_common_pb.ResponseMetadata.toObject(includeInstance, f),
    reportRequestState: jspb.Message.getFieldWithDefault(msg, 2, 0),
    userMessage: jspb.Message.getFieldWithDefault(msg, 3, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.medcrypt.helm.web.reports.GetReportRequestStateResponse}
 */
proto.medcrypt.helm.web.reports.GetReportRequestStateResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.medcrypt.helm.web.reports.GetReportRequestStateResponse;
  return proto.medcrypt.helm.web.reports.GetReportRequestStateResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.medcrypt.helm.web.reports.GetReportRequestStateResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.medcrypt.helm.web.reports.GetReportRequestStateResponse}
 */
proto.medcrypt.helm.web.reports.GetReportRequestStateResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new heim_common_pb.ResponseMetadata;
      reader.readMessage(value,heim_common_pb.ResponseMetadata.deserializeBinaryFromReader);
      msg.setMetadata(value);
      break;
    case 2:
      var value = /** @type {!proto.medcrypt.helm.web.enums.ReportRequestState} */ (reader.readEnum());
      msg.setReportRequestState(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setUserMessage(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.medcrypt.helm.web.reports.GetReportRequestStateResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.medcrypt.helm.web.reports.GetReportRequestStateResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.medcrypt.helm.web.reports.GetReportRequestStateResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.medcrypt.helm.web.reports.GetReportRequestStateResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getMetadata();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      heim_common_pb.ResponseMetadata.serializeBinaryToWriter
    );
  }
  f = message.getReportRequestState();
  if (f !== 0.0) {
    writer.writeEnum(
      2,
      f
    );
  }
  f = message.getUserMessage();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
};


/**
 * optional medcrypt.heimdall.web.common.ResponseMetadata metadata = 1;
 * @return {?proto.medcrypt.heimdall.web.common.ResponseMetadata}
 */
proto.medcrypt.helm.web.reports.GetReportRequestStateResponse.prototype.getMetadata = function() {
  return /** @type{?proto.medcrypt.heimdall.web.common.ResponseMetadata} */ (
    jspb.Message.getWrapperField(this, heim_common_pb.ResponseMetadata, 1));
};


/** @param {?proto.medcrypt.heimdall.web.common.ResponseMetadata|undefined} value */
proto.medcrypt.helm.web.reports.GetReportRequestStateResponse.prototype.setMetadata = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


proto.medcrypt.helm.web.reports.GetReportRequestStateResponse.prototype.clearMetadata = function() {
  this.setMetadata(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.medcrypt.helm.web.reports.GetReportRequestStateResponse.prototype.hasMetadata = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional medcrypt.helm.web.enums.ReportRequestState report_request_state = 2;
 * @return {!proto.medcrypt.helm.web.enums.ReportRequestState}
 */
proto.medcrypt.helm.web.reports.GetReportRequestStateResponse.prototype.getReportRequestState = function() {
  return /** @type {!proto.medcrypt.helm.web.enums.ReportRequestState} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/** @param {!proto.medcrypt.helm.web.enums.ReportRequestState} value */
proto.medcrypt.helm.web.reports.GetReportRequestStateResponse.prototype.setReportRequestState = function(value) {
  jspb.Message.setProto3EnumField(this, 2, value);
};


/**
 * optional string user_message = 3;
 * @return {string}
 */
proto.medcrypt.helm.web.reports.GetReportRequestStateResponse.prototype.getUserMessage = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/** @param {string} value */
proto.medcrypt.helm.web.reports.GetReportRequestStateResponse.prototype.setUserMessage = function(value) {
  jspb.Message.setProto3StringField(this, 3, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.medcrypt.helm.web.reports.GetReportFileRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.medcrypt.helm.web.reports.GetReportFileRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.medcrypt.helm.web.reports.GetReportFileRequest.displayName = 'proto.medcrypt.helm.web.reports.GetReportFileRequest';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.medcrypt.helm.web.reports.GetReportFileRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.medcrypt.helm.web.reports.GetReportFileRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.medcrypt.helm.web.reports.GetReportFileRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.medcrypt.helm.web.reports.GetReportFileRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    metadata: (f = msg.getMetadata()) && heim_common_pb.RequestMetadata.toObject(includeInstance, f),
    reportRequestId: (f = msg.getReportRequestId()) && heim_common_pb.UUID.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.medcrypt.helm.web.reports.GetReportFileRequest}
 */
proto.medcrypt.helm.web.reports.GetReportFileRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.medcrypt.helm.web.reports.GetReportFileRequest;
  return proto.medcrypt.helm.web.reports.GetReportFileRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.medcrypt.helm.web.reports.GetReportFileRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.medcrypt.helm.web.reports.GetReportFileRequest}
 */
proto.medcrypt.helm.web.reports.GetReportFileRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new heim_common_pb.RequestMetadata;
      reader.readMessage(value,heim_common_pb.RequestMetadata.deserializeBinaryFromReader);
      msg.setMetadata(value);
      break;
    case 2:
      var value = new heim_common_pb.UUID;
      reader.readMessage(value,heim_common_pb.UUID.deserializeBinaryFromReader);
      msg.setReportRequestId(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.medcrypt.helm.web.reports.GetReportFileRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.medcrypt.helm.web.reports.GetReportFileRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.medcrypt.helm.web.reports.GetReportFileRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.medcrypt.helm.web.reports.GetReportFileRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getMetadata();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      heim_common_pb.RequestMetadata.serializeBinaryToWriter
    );
  }
  f = message.getReportRequestId();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      heim_common_pb.UUID.serializeBinaryToWriter
    );
  }
};


/**
 * optional medcrypt.heimdall.web.common.RequestMetadata metadata = 1;
 * @return {?proto.medcrypt.heimdall.web.common.RequestMetadata}
 */
proto.medcrypt.helm.web.reports.GetReportFileRequest.prototype.getMetadata = function() {
  return /** @type{?proto.medcrypt.heimdall.web.common.RequestMetadata} */ (
    jspb.Message.getWrapperField(this, heim_common_pb.RequestMetadata, 1));
};


/** @param {?proto.medcrypt.heimdall.web.common.RequestMetadata|undefined} value */
proto.medcrypt.helm.web.reports.GetReportFileRequest.prototype.setMetadata = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


proto.medcrypt.helm.web.reports.GetReportFileRequest.prototype.clearMetadata = function() {
  this.setMetadata(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.medcrypt.helm.web.reports.GetReportFileRequest.prototype.hasMetadata = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional medcrypt.heimdall.web.common.UUID report_request_id = 2;
 * @return {?proto.medcrypt.heimdall.web.common.UUID}
 */
proto.medcrypt.helm.web.reports.GetReportFileRequest.prototype.getReportRequestId = function() {
  return /** @type{?proto.medcrypt.heimdall.web.common.UUID} */ (
    jspb.Message.getWrapperField(this, heim_common_pb.UUID, 2));
};


/** @param {?proto.medcrypt.heimdall.web.common.UUID|undefined} value */
proto.medcrypt.helm.web.reports.GetReportFileRequest.prototype.setReportRequestId = function(value) {
  jspb.Message.setWrapperField(this, 2, value);
};


proto.medcrypt.helm.web.reports.GetReportFileRequest.prototype.clearReportRequestId = function() {
  this.setReportRequestId(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.medcrypt.helm.web.reports.GetReportFileRequest.prototype.hasReportRequestId = function() {
  return jspb.Message.getField(this, 2) != null;
};


goog.object.extend(exports, proto.medcrypt.helm.web.reports);
